
public enum TileType {
	Path("path",true),
	Wall("wall",false),
	Shop0("pharmacy",true),
	Shop1("bookshop",true),
	Shop2("phone shop",true),
	Shop3("convenient stroe",true),
	Shop4("asian grocery",true),
	shop5("photocopy",true),
	shop6("optometrist",true),
	shop7("hair and beauty",true),
	Lounge0("general lounge",true),
	Lounge1("lot's wife lougne",true),
	Lounge2("waiting lounge",true),
	Lounge3("post grad lounge",true),
	Lounge4("airport lounge",true),
	Lounge5("MUISS lounge",true),
	Lounge6("microsoft lounge",true),
	Room0("commom room",true),
	Room1("meeting room",true),
	Room2("consult room",true),
	Room3("staff room",false),
	Room4("kitchen",false),
	Room5("music practice",true),
	Room6("yoga room",true),
	Room7("billiards room",true),
	Room8("renhersal room",true),
	Room9("dining room",true),
	Room10("computer lab",true),
	Room11("quite room",true),
	Room12("tea room",true),
	Room13("seminar room",true),
	Room14("dishwashing",false),
	Room15("consultation room",true),
	Room16("food preparation",true),
	Room17("band room",true),
	Room18("comm bank",true),
	Room19("vacant room",true),
	Restaurant0("joe's pizzeria",true),
	Restaurant1("joe's restaurant",true),
	Restaurant2("naptune fish and chip",true),
	Restaurant3("coffe wise",true),
	Restaurant4("peri peri",true),
	Restaurant5("boost juice",true),
	Restaurant6("wholefood restaurant",true),
	Restaurant7("sir john's bar",true),
	Toilet0("accessiable toilet",true),
	Toilet1("female toilet",true),
	Toilet2("male toilet",true),
	Toilet3("unisex toilet",true),
	Toilet4("general toilet",true),
	Toilet5("staff toilet",false),
	Banquet0("west banquet",true),
	Banquet1("centre banquet",true),
	Office0("general office",true),
	Office1("campus cntr manangement",true),
	Office2("grain express",true),
	Office3("library office",true),
	Office4("STA travel agency",true),
	Machine0("vending machine",true),
	
	//level 2
	level_106("Gneral Ancillary", false),
	level_109("Gneral Ancillary", false),
	level_1101("Gneral Ancillary", false),
	level_1110("Gneral Ancillary", false),
	level_1113("Gneral Ancillary", false),
	level_1121("Gneral Ancillary", false),
	level_1122A("Gneral Ancillary", false),
	level_1126("Gneral Ancillary", false),
	level_1133("Gneral Ancillary", false),
	level_1134("Gneral Ancillary", false),
	level_1152("Gneral Ancillary", false),
	level_128("Gneral Ancillary", false),
	level_129("Gneral Ancillary", false),
	level_158("Gneral Ancillary", false),
	level_164("Gneral Ancillary", false),
	level_166A("Gneral Ancillary", false),
	level_174("Gneral Ancillary", false),
	level_175("Gneral Ancillary", false),
	level_178A("Gneral Ancillary", false),
	level_180("Gneral Ancillary", false),
	level_185("Gneral Ancillary", false),
	level_185A("Gneral Ancillary", false),
	level_186("Gneral Ancillary", false),
	level_186A("Gneral Ancillary", false),
	level_187("Gneral Ancillary", false),
	level_191("Gneral Ancillary", false),
	level_192A("Gneral Ancillary", false),
	level_196A("Gneral Ancillary", false),
	level_198("Gneral Ancillary", false),
	level_101A("Lounge", true),
	level_1102("staff room", false),
	level_1118("Sir John's bar", true),
	level_112("lot's wife lounge", true),
	level_1120("general bar", true),
	level_1122("band room", true),
	level_1123("reception/wating", true),
	level_1125("broadcast room", true),
	level_113("lounge", true),
	level_1130("MUISS lounge", true),
	level_1130A("kitchen", false),
	level_1131("conference room", true),
	level_1138("lounge/waiting", true),
	level_114("quite room", true),
	level_1143("meeting room", true),
	level_1156("staff room", false),
	level_1158("meeting room", true),
	level_116("lounge", true),
	level_1168("photocopy", true),
	level_1171("seminar room", true),
	level_1173("tea room", true),
	level_1179("consultation", true),
	level_118("waiting room", true),
	level_120("meeting room", true),
	level_121("staff room", false),
	level_135("wating", true),
	level_140("staff room", false),
	level_141("meeting", true),
	level_153("conference", true),
	level_159C("kitchen", false),
	level_161("meeting room", true),
	level_166("wholefood restaurant", true),
	level_167("servery", false),
	level_170("post grad lounge", true),
	level_173("airport lounge/band", true),
	level_177("prep area", true),
	level_178("kitchen", false),
	level_179("dishwashing", false),
	level_181("wholefood servery", false),
	level_182("food preparation", false),
	level_188("east banquet", true),
	level_189("centre banquest", true),
	level_190("west banquet", true),
	level_196("dining room", true),
	level_197("drink servery", false),
	level_199("grain express", true),
	level_101B("quite study area", true),
	level_163("medley library", true),
	level_1103("female toilet", true),
	level_1104("male toilet", true),
	level_1105("accessiable toilet", true),
	level_1116("female toilet", true),
	level_1117("male toilet", true),
	level_1119("staff toilet", false),
	level_1121A("toilet", true),
	level_1154("toilet", true),
	level_168("male toilet", true),
	level_169("female toilet", true),
	level_193("male toilet", true),
	level_194("female toilet", true),
	level_195("accessiable toilet", true),
	level_LF01("lift01", true),
	level_LF02("life02", true),
	level_LF03("life03", true),
	level_LF04("life04", true),
	level_101("office", false),
	level_101C("office", false),
	level_102("office", false),
	level_103("office", false),
	level_105("office", false),
	level_107("office", false),
	level_108("lots wife", true),
	level_110("office", false),
	level_1108("ticket office", false),
	level_1109("office", false),
	level_111("office", false),
	level_1124("office", false),
	level_1127("office", false),
	level_1128("general office", false),
	level_1129("office", false),
	level_1135("office", false),
	level_1136("office", false),
	level_1137("office", false),
	level_1139("office", false),
	level_1140("office", false),
	level_1141("office", false),
	level_1144("office", false),
	level_1145("office", false),
	level_1146("office", false),
	level_1147("office", false),
	level_1149("office", false),
	level_1151("office", false),
	level_1153("office", false),
	level_1155("office", false),
	level_1157("office", false),
	level_1159("office", false),
	level_1160("office", false),
	level_1160A("office", false),
	level_1161("office", false),
	level_1162("office", false),
	level_1163("office", false),
	level_1164("office", false),
	level_1165("office", false),
	level_1166("reception", true),
	level_1167("general office", false),
	level_1169("office", false),
	level_117("office", false),
	level_1170("office", false),
	level_1172("office", false),
	level_1174("office", false),
	level_1175("office", false),
	level_1176("office", false),
	level_1177("office", false),
	level_1178("office", false),
	level_119("office", false),
	level_123("office", false),
	level_124("office", false),
	level_125("office", false),
	level_126("office", false),
	level_127("office", false),
	level_130("general office", false),
	level_131("office", false),
	level_132("office", false),
	level_133("office", false),
	level_134("office", false),
	level_136("office", false),
	level_137("office", false),
	level_138("office", false),
	level_142("reception", true),
	level_145("office", false),
	level_146("office", false),
	level_147("office", false),
	level_148("office", false),
	level_149("office", false),
	level_151("office", false),
	level_152("office", false),
	level_155("office", false),
	level_157("office", false),
	level_159("Campus Cntr Mgmnt", false),
	level_159B("office", false),
	level_160("office", false),
	level_162("office", false),
	level_165("library office", false),
	level_171A("office", false),
	level_171B("office", false),
	level_171C("office", false),
	level_184("office", false);

	
	String roomName;
	boolean walkable;
	
	TileType(String roomName, boolean walkable){
		this.roomName = roomName;
		this.walkable = walkable;
	}
}
